export const FILLER_TOKENS = new Set([
  'a', 'about', 'above', 'across', 'after', 'again', 'against', 'ago', 'all',
  'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am',
  'among', 'an', 'and', 'another', 'any', 'anybody', 'anyone', 'anything',
  'anywhere', 'are', 'around', 'as', 'aside', 'at', 'away', 'back', 'be',
  'because', 'become', 'becomes', 'becoming', 'been', 'before', 'behind',
  'being', 'below', 'beneath', 'beside', 'besides', 'between', 'beyond',
  'both', 'briefly', 'but', 'by', 'can', 'cannot', 'cant', 'certain', 'clearly',
  'co', 'could', 'couldnt', 'currently', 'definitely', 'despite', 'did',
  'didnt', 'do', 'does', 'doesnt', 'doing', 'done', 'down', 'during', 'each',
  'either', 'else', 'elsewhere', 'enough', 'especially', 'even', 'ever',
  'every', 'everybody', 'everyone', 'everything', 'everywhere', 'few',
  'finally', 'for', 'former', 'formerly', 'forth', 'from', 'further', 'get',
  'gets', 'getting', 'give', 'given', 'gives', 'go', 'goes', 'going', 'gone',
  'got', 'gotten', 'had', 'hadnt', 'has', 'hasnt', 'have', 'havent', 'having',
  'he', 'hed', 'hell', 'hes', 'her', 'here', 'heres', 'hers', 'herself', 'him',
  'himself', 'his', 'how', 'however', 'i', 'id', 'ill', 'im', 'ive', 'if',
  'immediate', 'in', 'indeed', 'inside', 'into', 'is', 'isnt', 'it', 'itd',
  'itll', 'its', 'itself', 'just', 'least', 'less', 'let', 'lets', 'like',
  'likely', 'mainly', 'many', 'may', 'maybe', 'me', 'meanwhile', 'might',
  'more', 'most', 'mostly', 'much', 'must', 'my', 'myself', 'near', 'nearly',
  'neither', 'never', 'nevertheless', 'next', 'no', 'nobody', 'none', 'nor',
  'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one',
  'only', 'onto', 'or', 'other', 'others', 'otherwise', 'ought', 'our',
  'ours', 'ourselves', 'out', 'outside', 'over', 'own', 'per', 'perhaps',
  'quite', 'rather', 'really', 'same', 'seem', 'seemed', 'seeming', 'seems',
  'several', 'shall', 'she', 'shed', 'shell', 'shes', 'should', 'shouldnt',
  'since', 'so', 'some', 'somebody', 'someone', 'something', 'sometime',
  'sometimes', 'somewhere', 'soon', 'still', 'such', 'than', 'that', 'thats',
  'the', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there',
  'theres', 'therefore', 'these', 'they', 'theyd', 'theyll', 'theyre', 'theyve',
  'this', 'those', 'though', 'through', 'throughout', 'thus', 'till', 'to',
  'too', 'toward', 'towards', 'under', 'underneath', 'unless', 'until', 'unto',
  'up', 'upon', 'us', 'very', 'via', 'was', 'wasnt', 'we', 'wed', 'well',
  'were', 'werent', 'weve', 'what', 'whats', 'whatever', 'when', 'whence',
  'whenever', 'where', 'wheres', 'whereas', 'whereby', 'wherein', 'wherever',
  'whether', 'which', 'while', 'whither', 'who', 'whod', 'whoever', 'whole',
  'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'wont', 'would',
  'wouldnt', 'yes', 'yet', 'you', 'youd', 'youll', 'youre', 'youve', 'your',
  'yours', 'yourself', 'yourselves', 'zero',
])
